# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Minse Ha
title: Vision AI developer / Senior - Kyungpook National University / VIS Lab
email: haminse@gmail.com
# email_title: Email (Email title override)
phone: 010-3712-8575
# phone_title: Phone (Phone title override)
website: https://aminss.tistory.com
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
github_username: haminse
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: min_n_se
linkedin_username: haminse
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"


  # for in about contents
  # You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
  #   - Lists
  #   - Tables
  #   - <a href="google.com">Links</a>
  #   - Images ![alt text](/images/landscape-trees.jpg "Trees")

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello! I'm Minse Ha, an AI engineer specializing in computer vision, with a focus on object detection, segmentation, and multi-modal applications. 
  Currently based in the Vision Intelligence Lab in Korea, I thrive on leveraging data and AI to foster effective communication and drive innovation 
  in the field of artificial intelligence. Passionate about creating intelligent systems, I am dedicated to pushing the boundaries of what's possible 
  in computer vision technology. I have skills with <mark>Python</mark> <mark>Pytorch</mark> <mark>Tensorflow</mark> <mark>Flask</mark> <mark>MySQL</mark> <mark>Linux/Git</mark>
  and <mark>JS/HTML/CSS</mark>

  You can check my web development projects here. [LINK](https://minse-web-dev-total.netlify.app/)

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: AI voice route guidance service for the elderly
        link: https://drive.google.com/file/d/1i55jWuRN0tI_r2pZVCLvDDT3Wq34t1tA/view?usp=sharing
        link_text: Slides
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: https://github.com/haminse/AI-route-guidance-callcenter-4-elderly
        quote: >
          Implement AI voice route guidance service for the elderly to solve social problem
        description: | # this will include new lines to allow paragraphs
          - Lead a project to develop an AI voice route guidance service for the elderly and transportation-vulnerable, enhancing their travel independence. Integrating Chat GPT, Google's STT and TTS APIs, Google Maps, and Weather APIs, we created a seamless journey-guidance system. The project emphasized user-friendly design, significantly aiding users with limited digital literacy.
          - Got the grand prize in 2023 Korea association of Information Systems Fall Conference College Student Idea Contest.
    # content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Solution for recycling waste classification domain
        link: https://github.com/knu-on-plus/Recycling_Waste_Detector
        link_text: Supplementary page
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: https://github.com/knu-on-plus/Data-generation-solution-for-recycling-waste-classification
        quote: >
          Implements AI for detecting recycled waste and presents solutions to data shifting problems
        description: | # this will include new lines to allow paragraphs
          - With the goal of automating waste sorting, developed a real-time recycling waste detection model using YOLOv8. 
          - Improved detection model F1score 6% by resolving data imbalance through the Segmented-Crop&Paste method using SAM (Segment Anything Model, Meta). 
          - Won the grand prize at the industry-university cooperation project contest.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Internship
        sub_title: Data Analysis intern
        caption: Oct 2022 - Aug 2023
        link: https://aminss.tistory.com/45
        quote: >
          Brain bitamin retail company
        description: | # this will include new lines to allow paragraphs
          - Customer Data Analysis/Visualization for offline store location selection
          - Preprocess company's data with python and data crawling methods
          - Process Automization(Blogging automization, Customer consultation automation)
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: KNU
        sub_title: BS Artificial Intelligence
        caption: 2017 - 2023
        quote: >
          Departement of Electrical engineering 
        description: | # this will include new lines to allow paragraphs
          Deep learning, Data structure & algorithms, Pattern Recognization, AI Programming, Linear Algebra/Statistic 
  - title: AWARDS
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Received the <b>1st</b> prize at the ICT Intellectual Property Association College Student Entrepreneurship Hackathon
      - Received the <b>2nd</b> prize in the brain aneurysm screening artificial intelligence competition hosted by K-ium
      - Received the <b>3rd</b> prize in Daegu City Public Problem Solving Software Development Hackathon
      - Recieved the <b>3rd</b> prize in KOVA Venture Business Association Capstone Design Contest

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
