# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Minse Ha
title: Vision AI developer / M.S. Student - Kyungpook National University / VIS Lab
email: haminse@gmail.com
# email_title: Email (Email title override)
phone: 010-3712-8575
# phone_title: Phone (Phone title override)
website: https://aminss.tistory.com
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
github_username: haminse
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: min_n_se
linkedin_username: haminse
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"


  # for in about contents
  # You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
  #   - Lists
  #   - Tables
  #   - <a href="google.com">Links</a>
  #   - Images ![alt text](/images/landscape-trees.jpg "Trees")

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello! I'm Minse Ha, an AI developer specializing in computer vision, with a focus on object detection, segmentation, and multi-modal applications. 
  Currently based in the Vision Intelligence Lab in Korea, I thrive on leveraging data and AI to foster effective communication and drive innovation 
  in the field of artificial intelligence. Passionate about creating intelligent systems, I am dedicated to pushing the boundaries of what's possible 
  in computer vision technology. I have skills with 
  
  <mark>Python</mark> <mark>Pytorch</mark> <mark>Tensorflow</mark> <mark>Flask</mark> <mark>Docker/Conda</mark> <mark>Linux/Git</mark>
  and <mark>JS/HTML/CSS</mark>



content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: AI voice route guidance service for the elderly
        link: https://drive.google.com/file/d/1i55jWuRN0tI_r2pZVCLvDDT3Wq34t1tA/view?usp=sharing
        link_text: Slides
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: https://github.com/haminse/AI-route-guidance-callcenter-4-elderly
        quote: >
          <b>Implement AI voice route guidance service for the elderly to solve social problem</b>
        description: | # this will include new lines to allow paragraphs
          - Lead a project to develop an AI voice route guidance service for the elderly and transportation-vulnerable, enhancing their travel independence. 
          - Integrated Chat GPT, Google's STT and TTS APIs, Google Maps, and Weather APIs.
          - Created elderly-friendly design, significantly aiding users with limited digital literacy.
          - Got the grand prize[1st] in 2023 Korea association of Information Systems Fall Conference College Student Idea Competition.
      
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Recycling waste detection 
        link: https://github.com/knu-on-plus/Recycling_Waste_Detector
        link_text: Supplementary page
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: https://github.com/knu-on-plus/Data-generation-solution-for-recycling-waste-classification
        quote: >
          <b>Built AI model for detecting recycled waste and presents solutions to resolve data shifting problems</b>
        description: | # this will include new lines to allow paragraphs
          - With the goal of automating waste sorting, developed a real-time recycling waste detection model using YOLOv8. 
          - Improved detection model F1score 6% by resolving data imbalance problem through the Segmented-Crop&Paste method using SAM (Segment Anything Model, Meta). 
          - Cooperate with [WIM](https://www.wimcorp.co.kr/), an integrated solutions company in the field of intelligent control as an intern.
          - Won the grand prize[1st] at the Industry-Academia Cooperation Project Competition.

      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Howdinn - Video Diary web service with AI Advisor
        link: https://drive.google.com/file/d/11510fH56YOJJbntdeQeGr_Dgc75YrsYS/view?usp=sharing
        link_text: Slides
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: https://github.com/haminse/Howdinn
        quote: >
          <b>Development of a video web diary service that supports AI sentiment analysis and counseling</b>
        description: | # this will include new lines to allow paragraphs
          - Developed the concept for an AI concierge service utilizing video diaries to analyze and respond to user needs.
          - Combined Hume API and ChatGPT-4 for sentiment analysis and recommendations, incorporating a Flask server and frontend integration for sentimental insight from user's video.
          - Worked with a team of diverse cultural backgrounds.

# content:
  - title: Experiences
    layout: list
    content:
      - layout: left
        title: Data Analysis intern
        sub_title: Internship in HealthyLike, Daegu, Korea
        caption: Oct 2022 - Aug 2023
        link: http://hlike.asadesign.kr/
        quote: >
          <b>Data analysis intern in bitamin retail company</b>
        description: | # this will include new lines to allow paragraphs
          - Customer Data Analysis/Visualization for offline store location selection. [LINK](https://aminss.tistory.com/45)
          - Preprocess company's data with python and data crawling methods.
          - Conducted with work customer consultation automation.
  
      - layout: left
        title: Vision AI engineer intern 
        sub_title: Internship in WIM, Daegu, Korea
        caption: July 2023 - Present
        link: https://www.wimcorp.co.kr/
        quote: >
          <b>Implementation and weight reduction of vision model for automatic crop harvesting robot</b>
        description: | # this will include new lines to allow paragraphs
          - Working on OS setup and maintenance with Stereolabs ZED box and camera settings.
          - Developing a 2D crop segmentation & depth estimation model for enhancing harvesting robot recognition capabilities.
          - Implementing a lightweight model and conducting methodological research for its application in a robotic environment.

      - layout: left
        title: Student Ambassador
        sub_title: KSA - Kyungpook national university Student Ambassador
        caption: June 2020 - June 2021
        link: https://www.youtube.com/@knuoia
        quote: >
          <b>Management and event planning for 200+ international students per semester</b>
        description: | # this will include new lines to allow paragraphs
          - Planning and operating cultural exchange online seminars and events for international students every month.
          - Develop communication skills and English skills with people from diverse cultures
          - Despite the coronavirus pandemic, achieved more than 80% satisfaction in the exchange student satisfaction survey.

  - title: Education
    layout: list
    content:
      - layout: left #top-right
        title: M.S. of Computer Science in VIS Lab
        sub_title: Kyungpook National University
        caption: March, 2024 - Present
        quote: >
          <b>Computer Science, department of Information Technology</b>
        description: | # this will include new lines to allow paragraphs
          - About the VIS Lab (Vision & Intelligence System Lab): [LINK](https://sites.google.com/view/k-vislab/home?authuser=0)
          - Developing action recognition dataset and conducting algorithm research to enhance surveillance robot recognition performance.
          - Researching multimodal algorithms based on camera & sensor fusion technology for rehabilitation exercise assistance.

      - layout: left #top-right
        title: B.S. Computer Science, Artificial intelligence
        sub_title: San Jose State University 
        caption: Jul, 2022 - Jun, 2023
        quote: >
          <b>Exchange student in SJSU</b>
        description: | # this will include new lines to allow paragraphs
          - Topics in machine learning, Deep learning, Python data analysis, Data visualization, Server-side web programming
          - Joined the [ML@SJSU](https://mlatsjsu.com/) club and led the Photo Retouching Service with Style Transfer Model project. [LINK](https://drive.google.com/file/d/1A7ny6qcyKsmofY_1DWbKnFrizIzbgjr-/view?usp=sharing)
          - Took a part in LikeLion-SJSU web development club and conducted with various web development. [LINK](https://minse-web-dev-total.netlify.app/)
          - Conducted research about bay area house price prediction. [LINK](https://drive.google.com/file/d/1nMyYv7we95KCEWHErowyK0sqlBG6JZ9y/view)
          - Participated in Cal Hackhathon hosted by Berkely university with international teammates [LINK](https://github.com/haminse/Howdinn)

      - layout: left #top-right
        title: B.S. of Artificial Intelligence 
        sub_title: Kyungpook National University
        caption: Mar, 2017 - Feb, 2024
        quote: >
          <b>Departement of Electrical engineering</b>
        description: | # this will include new lines to allow paragraphs
          Deep learning, Data structure & algorithms, Pattern Recognization, AI Programming, Linear Algebra/Statistic
      
  
  - title: AWARDS
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Won the <b>1st</b> prize at the <b>Industry-Academia Cooperation Project Competition</b>
      - Won the <b>1st</b> prize at the <b>2023 Korea association of Information Systems Fall Conference College Student Idea Competition</b>
      - Won the <b>2nd</b> prize in the <b>brain aneurysm screening artificial intelligence competition hosted by K-ium</b>
      - Won the <b>3rd</b> prize in <b>Daegu City Public Problem Solving Software Development Hackathon hosted by KNU</b>
      - Won the <b>3rd</b> prize in <b>KOVA Venture Business Association Capstone Design competition</b>
      - Won the <b>3rd</b> prize in <b>K-Digital Platform Living Lab Idea Contest</b>

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
